name: Continuous Integration
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build
        run: |
          make build
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Upload artifact psycopg2
        uses: actions/upload-artifact@v2
        with:
          name: psycopg2
          path: psycopg2/package.zip

